dist: focal

language: php

services:
  - mongodb
  - postgresql

addons:
  sonarcloud:
    organization: "chubbyphp"

git:
  depth: false

matrix:
  include:
    - php: 7.4
      env: composerargs="--prefer-lowest"
    - php: 7.4
    - php: 8.0

before_script:
  - while ! nc -z localhost 5432; do sleep 0.1; done # wait for postgresql
  - psql -c 'CREATE USER root WITH ENCRYPTED PASSWORD 'root' CREATEDB;' -U postgres
  - while ! nc -z localhost 27017; do sleep 0.1; done # wait for mongodb
  - mongo admin --eval 'db.createUser({user:"root",pwd:"root",roles:["root"]});'
  - echo 'extension=mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/mongodb.ini
  - (phpenv config-rm xdebug.ini || exit 0)
  - pecl install pcov
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - composer update $composerargs -n

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=build/phpunit/clover.xml --json_path=build/coveralls.json -v
  - sonar-scanner
